### ISSUE TITLE
Improved package support/modularization

### ISSUE THREAD

**Issue by AdamIsrael** [juju-solutions/layer-basic#74]
The way the layer currently handles packages is inconsistent. Packages to be installed via apt are placed into layers.yaml, but python packages are in wheelhouse.txt, and there's no support for other packaging formats, such as snaps or npm.

A more modular approach would allow developers to write support for a particular packaging format, with a consistent way to install them. Two possible formats of layers.yaml to support this idea:

```yaml
options:
  basic:
    packages:
      - apt:traceroute
      - pip:paramiko==2.0.1
      - npm:grunt
      - npm:grunt-cli
      - snap:hello-world
```

```yaml
options:
basic:
  packages:
    apt:
        - traceroute
    pip:
        - paramiko==2.0.1
    npm:
        - grunt
        - grunt-cli
    snap:
        - hello-world
```

**Comment by marcoceppi** [comment]
totally +1 to this.

**Comment by stub42** [comment]
Do we want to be able to specify if packages are:

- embedded as an architecture dependent binary?
- embedded in source form?
- downloaded at install/update time from 'Net?
- downloaded at install/update time as resources?

If so, pick a syntax that can support this.

**Comment by marcoceppi** [comment]
Thinking about this more, npm is a very specific type of package management, same with snap. You'd pretty much need an apt, npm layer, etc to install these. Where python/pip are already always available on all basic layer installs.

So I'm a plus one on:

```yaml
options:
  basic:
    packages:
      apt:
        - pkg
      pip:
        - pkg==99.9
```

Then snap layers, or npm, or whatever, can build their own tactics for managing this in their layers.
